name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and push Docker images
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
    
